# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.4.0-cli

before_script:
    - apt-get update -yqq
    - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev zip unzip
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.email "bot@finally-a-fast.com"
    - git config --global user.name "FAF Bot"

stages:
    - build
    - git-robot

build:
    stage: build
    only:
        - master
    script:
        - touch test.txt

git-rebase-ts:
    stage: git-robot
    only:
        - master
    allow_failure: true
    script:
        - git clone git@gitlab.com:${CI_PROJECT_PATH}.git
        - cd ${CI_PROJECT_NAME}
        - git checkout ts
        - git rebase master
        - git push --force origin ts
