stages:
    - build
    - git-robot

build:
    stage: build
    only:
        - master
    script:
        - touch test.txt

git-rebase-ts:
    stage: git-robot
    only:
        - master
    allow_failure: true
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
        - git config --global user.email "bot@finally-a-fast.com"
        - git config --global user.name "FAF Bot"
        - mkdir -p ~/.ssh
        - cat gitlab-known-hosts >> ~/.ssh/known_hosts
    script:
        - git clone git@gitlab.com:${CI_PROJECT_PATH}.git
        - cd ${CI_PROJECT_NAME}
        - git checkout ts
        - git rebase master
        - git push --force origin ts
